# Workflow to build the package using ROS2 and PX4
name: Setup and build package
on:
  push:
    branches:
      - main

env:
  USER: github.actor
jobs:
    setup_px4:
        runs-on: ubuntu-latest
        container:
            image: px4io/px4-dev-ros2-galactic:2021-09-08
            options: --privileged --ulimit core=-1 --security-opt seccomp=unconfined
        steps:
        - uses: actions/checkout@v4
