# Workflow to build the package using ROS2 and PX4 within a Docker container
name: Setup and build package
on:
  push:
    branches:
      - main

env:
  USER: github.actor
jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: osrf/ros:humble-desktop
        steps:

        - name: Check environment
          run: |
            export
            ulimit -a

        - name: Check ROS2 command
          run: |
            source /opt/ros/humble/setup.bash
            ros2 --help

        - name: Create a new workspace
          run: |
            cd ~
            mkdir -p llc/llc_ws/src

        - name: Setup PX4-Autopilot
          run: |
            cd ~/llc
            git clone https://github.com/PX4/PX4-Autopilot.git
            cd ~/llc/PX4-Autopilot
            make px4_sitl_default

        - name: Head to src directory of workspace
          run: |
            cd ~/llc/llc_ws/src
        
        - name: Check out code repository
          uses: actions/checkout@v4

        - name: Clone px4_msgs repository
          run: |
            cd ~/llc/llc_ws/src
            git clone https://github.com/PX4/px4_msgs.git

        - name: Build package
          run: |
            cd ~/llc/llc_ws
            source /opt/ros/galactic/setup.bash
            colcon build --symlink-install