# Workflow to build the package using ROS2 and PX4
name: Setup and build package
on:
  push:
    branches:
      - main

env:
  USER: github.actor
jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: px4io/px4-dev-ros2-galactic:2021-09-08
            options: --privileged --ulimit core=-1 --security-opt seccomp=unconfined
        steps:
        - uses: actions/checkout@v4

        - name: Install gazebo
          run: |
            ls -l
            apt update && apt install -y gazebo11 libgazebo11-dev gstreamer1.0-plugins-bad gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly libgstreamer-plugins-base1.0-dev

        - name: Clean the PX4 directory
          run: |
            make clean
            make distclean
        
        - name: Build PX4 with Gazebo
          run: |
            make px4_sitl gz_x500
