# Workflow to build the package using ROS2 and PX4 within a Docker container
name: Setup and build package
on:
  push:
    branches:
      - main

env:
  USER: github.actor
jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: px4io/px4-dev-ros2-galactic:2021-09-08
            options: --privileged --ulimit core=-1 --security-opt seccomp=unconfined
        steps:
        
        - name: Create a new workspace
          run: |
            cd ~
            mkdir -p llc/llc_ws/src

        - name: Setup PX4-Autopilot
          run: |
            cd ~/llc
            git clone https://github.com/PX4/PX4-Autopilot.git
            cd ~/llc/PX4-Autopilot/Tools/setup
            ./ubuntu.sh

        - name: Build SITL
          run: |
            cd ~/llc/PX4-Autopilot
            make px4_sitl_default gazebo-classic

        - name: Head to src directory of workspace
          run: |
            cd ~/llc/llc_ws/src
        
        - name: Check out code repository
          uses: actions/checkout@v4

        - name: Clone px4_msgs repository
          run: |
            cd ~/llc/llc_ws/src
            git clone https://github.com/PX4/px4_msgs.git

        - name: Build package
          run: |
            cd ~/llc/llc_ws
            colcon build --symlink-install